import './globals.css'
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <body>
        <Nav />
        <main>{children}</main>
        <Footer />
      </body>
  )
}
