import './globals.css'
import Footer from "@/components/Footer";
import {Metadata} from "next";
import {FC, ReactNode} from "react";
import {i18n} from "@/i18n/config";
import i18nStore from "@/store/i18n.store";
import {getDictionary} from "@/i18n/get-dictionary";
import Providers from "./providers";

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

interface RootLayoutProps {
    children: ReactNode,
    params: {
        lang: typeof i18n['locales'][number]
    }
}

const RootLayout = async ({children, params: {lang}}: RootLayoutProps) => {
    i18nStore.setState({locale: lang, dictionary: await getDictionary(lang)})
    return (
            <html lang="en">
                <head>
                    <link rel="icon" href="/favicon.ico"/>
                </head>
                <body>
                <Providers><main>{children}</main>
                    <Footer/></Providers>
                </body>
            </html>
    )
}

export default RootLayout

export function generateStaticParams() {
    return i18n.locales.map(locale => ({lang: locale}))
}
